version: '2'
services:
  image-server:
    image: quay.io/azavea/scala:2.11.8
    ports:
      - "9000:9000"
    volumes:
      - ./:/opt/gt-image-correction/
      - ./.ivy2:/root/.ivy2
      - ./.sbt:/root/.sbt
    working_dir: /opt/gt-image-correction/
    command: ./sbt server/run
    # environment:
    #   - SBT_OPTS="-Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=6G -Xss2M"

  nginx:
    image: nginx:1.11-alpine
    ports:
      - "9100:443"
    volumes:
      - ./nginx/srv/dist/:/srv/dist/
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
